<?php /** @var \Neklo\News\Block\ArticlesCategory $block */ ?>
<?php if ($block->canShow()) : ?>
    <h1 style="text-align: center"><?=  $block->escapeHtml($block->getCategory()->getCategory()) ?></h1>
    <br>
    <a href="<?= $block->getPartUrlNews() ?>">back</a>
    <?php $prefix = $block->getPrefix() ?>
    <?php foreach ($block->getArticleCategory() as $article) : ?>
        <div style="background-color: #dcdbdb; margin: 10px;text-align: center">
            <p>title<span><?=  $block->escapeHtml($article->getTitle()) ?></span></p>
            <p>content<span><?=  $block->escapeHtml($article->getContent()) ?></span></p>
            <p><a href="<?=  $block->escapeHtml($block->getAticleWithCatategory($article->getData('url_key'))) ?>">look</a></p>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
