<?php /** @var \Neklo\News\Block\Article $block */?>
<table border="1px">
    <thead>
    <tr>
        <td>title</td>
        <td>content</td>
        <td>is_active</td>
        <td>look</td>
    </tr>
    </thead>
    <tbody>
    <h2><?=  $block->escapeHtml($block->getNameTable())?></h2>
    <?php foreach ($block->getNews() as $item) :?>
        <tr>
            <td><?=  $block->escapeHtml($item->getTitle()) ?></td>
            <td><?=  $block->escapeHtml($item->getContent()) ?></td>
            <td><?=  $block->escapeHtml($item->getData('is_active')) ?></td>
            <td><a target="_blank" href="<?= $block->getUrlArticle($item->getData('category_name'), $item->getData('url_key')) ?>">look</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


