<?php /** @var \Neklo\News\Block\Article $block */?>
<table border="1px">
    <thead>
    <tr>
        <td>title</td>
        <td>content</td>
        <td>is_active</td>
        <td>look</td>
    </tr>
    </thead>
    <tbody>
    <h2><?= $block->getNameTable()?></h2>
    <?php foreach ($block->getNews() as $item) :?>
        <tr>
            <td><?= $item->getTitle() ?></td>
            <td><?= $item->getContent() ?></td>
            <td><?= $item->getData('is_active') ?></td>
            <td><a target="_blank" href="<?= $block->getUrlArticle($item->getData('nnc_name_getegory'), $item->getData('url_key')) ?>">look</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


